name: RobotFramework API Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all the branches
  push:
    branches: [ "**" ]

jobs:
  robot-framework:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@master # THIS IS IMPORTANT
      - uses: actions/setup-python@v3 # THIS IS IMPORTANT
        with:
          python-version: '3.10'
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          deps_list: 'requirements.txt'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Show library versions
        run: |
          python3 --version
      - name: Robot Framework Tests
        run: |
          robot --outputdir robot-test-results test_cases
      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: robot-test-results